# make-silent-launcher.ps1 — 通用工具:把计划任务改成静默启动(消除窗口闪现)
#
# 用法(管理员 PowerShell):
#   .\make-silent-launcher.ps1 -TaskName 'MyTask' -ScriptPath 'C:\x\my-script.ps1'
#
# 可选:
#   -KeepArgs '<原命令行参数>'   在 VBS 里追加额外参数
#   -DryRun                     只打印将要做什么,不修改
#
# 原理: 把 Task To Run 从 powershell.exe/cmd.exe 换成 wscript.exe //B //Nologo <vbs>,
#       VBS 再以"完全隐藏、不等待"方式拉起原脚本。触发器/Settings/Principal 原样保留,
#       因此看门狗的崩溃恢复能力不受影响。
#
# 前置: 目标任务的 Execute 必须是控制台程序,否则本来就不闪,无需处理。

param(
    [Parameter(Mandatory = $true)][string]$TaskName,
    [Parameter(Mandatory = $true)][string]$ScriptPath,
    [string]$KeepArgs = '',
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch {}

function Say {
    param([string]$Msg, [string]$Color = 'Cyan')
    Write-Host $Msg -ForegroundColor $Color
}

# ---------- 权限 ----------
$admin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $admin) {
    Say '[X] 需要管理员权限' 'Red'
    Say '    请右键 bat 以管理员运行,或在管理员 PowerShell 里执行本脚本。' 'Yellow'
    exit 1
}

# ---------- 前置检查 ----------
if (-not (Test-Path $ScriptPath)) {
    Say "[X] 脚本不存在: $ScriptPath" 'Red'
    exit 1
}

try {
    $svc = New-Object -ComObject 'Schedule.Service'
    $svc.Connect()
    $root = $svc.GetFolder('\')
    $t = $svc.GetTask($TaskName)
} catch {
    Say "[X] 读不到任务 '$TaskName': $($_.Exception.Message)" 'Red'
    exit 1
}

$oldExec  = $t.Actions.Item(1).Path
$oldArgs  = $t.Actions.Item(1).Arguments
$logonType = $t.Principal.LogonType

Say '===== 当前任务 =====' 'Cyan'
Say "  TaskName  = $TaskName"
Say "  Execute   = $oldExec"
Say "  Arguments = $oldArgs"
Say "  LogonType = $logonType"

# 已是无声启动则无需处理
if ($oldExec -match 'wscript\.exe|cscript\.exe') {
    Say ''
    Say '[OK] 已经是 wscript/cscript 静默启动,无需修改。' 'Green'
    exit 0
}

# ---------- 生成 VBS ----------
$vbsDir  = Split-Path $ScriptPath -Parent
$vbsName = [System.IO.Path]::GetFileNameWithoutExtension($ScriptPath) + '-hidden-launcher.vbs'
$vbsPath = Join-Path $vbsDir $vbsName

$cmdLine = "powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$ScriptPath`""
if ($KeepArgs) { $cmdLine += " $KeepArgs" }
# VBS 内部双引号需转义为两个双引号
$cmdLineEscaped = $cmdLine.Replace('"', '""')

$vbs = @"
' Silent launcher: $TaskName
' Eliminates console-window flash on every scheduled trigger.
' Generated by make-silent-launcher.ps1 - do not edit while task is running.
Option Explicit
Dim shell
Set shell = CreateObject("WScript.Shell")
shell.Run "$cmdLineEscaped", 0, False
"@

Say ''
Say '===== 即将写入 VBS =====' 'Cyan'
Say "  $vbsPath"
$vbs -split "`r?`n" | ForEach-Object { Say "    $_" }

$newExec  = 'wscript.exe'
$newArgs  = "//B //Nologo `"$vbsPath`""

if ($DryRun) {
    Say ''
    Say '[DryRun] 不做实际修改。去掉 -DryRun 再执行即可生效。' 'Yellow'
    exit 0
}

# ---------- 写 VBS(必须 ASCII 无 BOM)----------
[System.IO.File]::WriteAllText($vbsPath, $vbs, (New-Object System.Text.ASCIIEncoding))
$b = [System.IO.File]::ReadAllBytes($vbsPath)
Say ''
Say ("[OK] VBS 已写入({0} 字节, BOM={1})" -f $b.Length, ($b[0] -eq 0xEF)) 'Green'

# ---------- 改任务 Action(COM 保留其余配置)----------
$a = $t.Actions.Create(0)
$a.Path = $newExec
$a.Arguments = $newArgs

$t.RegistrationInfo.Description = "$TaskName (silent launcher: wscript.exe, no console flash on trigger)"

$root.RegisterTaskDefinition($TaskName, $t, 6, $null, $null, $logonType, $null) | Out-Null

# ---------- 复验 ----------
$t2 = $svc.GetTask($TaskName)
Say ''
Say '===== 修改后 =====' 'Cyan'
Say "  Execute   = $($t2.Actions.Item(1).Path)"
Say "  Arguments = $($t2.Actions.Item(1).Arguments)"

# 确认触发器还在(关键:不能把看门狗周期改没了)
$trigCount = 0
try { $trigCount = $t2.Triggers.Count } catch {}
Say "  Triggers  = $trigCount 个(应与修改前一致)"

Say ''
Say '[OK] 已改为静默启动。原有触发器/看门狗逻辑保持不变。' 'Green'
Say '提示: 等一个完整触发周期(看 Repeat 的间隔)观察是否还闪窗。' 'Gray'